name: Deploy Documentation

# Trigger the workflow on push to the default branch or when manually triggered
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx_rtd_theme

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: List the build output directory
      run: |
        ls -R docs/_build/html  # List files to ensure that the build directory is created

    - name: Upload artifact
      uses: actions/upload-artifact@v4 
      with:
        name: documentation
        path: docs/_build/html  # Upload the build output as an artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4  # Corrected to v3
      with:
        name: documentation  # Ensure artifact is downloaded

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: documentation  # Specify the artifact name to deploy
      env:
        ACTIONS_RUNNER_DEBUG: true
        ACTIONS_STEP_DEBUG: true