name: Deploy Documentation

# Trigger the workflow on push to the default branch or when manually triggered
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: read
  actions: read  # Ensure the actions have read permissions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx_rtd_theme

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: List the build output directory
      run: |
        ls -R docs/_build/html  # List files to ensure the build directory is created

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: docs/_build/html  # Directly specify the folder to deploy